### ISSUE TITLE
Repository naming strategy

### ISSUE THREAD

**Issue by chriscoffee** [NHSLeadership/nightingale-moodle#27]
We're currently installing this plugin using composer with composer/installers. This references the `"type": "moodle-theme",` within the composer.json file and installs it into `/themes/`

However, due to the name of the repository it installs the repository as `/themes/theme_nightingale`. This is a problem due to how the name of the theme has been hardcoded. The theme is looking for the folder name to be `nightingale` and not `theme_nightingale`.

**Comment by ishanivardhan** [comment]
Closing this issue now as the Git repository is renamed as "moodle-theme_nightingale" keeping composer requirements in mind & we have also used this convention to clone the theme for Moodle staging latest site.

We can create separate issues, if any composer requirements have still not been met & needs further work.
