### ISSUE TITLE
Assignment Pages Design

### ISSUE THREAD

**Issue by ishanivardhan** [NHSLeadership/nightingale-moodle#65]
Hi @jdbrew , @cehwitham 

In @Pro-Paul 's absence I would like to know your viewpoint on design perspective for Assignment pages.

- This includes what Assignment pages/screens would a student come in contact with? 
- How we can tidy up those Assignment pages in absence of a specific design?

Please login to Moodle Staging site for your reference to see the existing state of Assignment pages that needs work.

[http://moodle-staging.nhsx.uk/mod/turnitintooltwo/view.php?id=2276](http://moodle-staging.nhsx.uk/mod/turnitintooltwo/view.php?id=2276)

**Comment by jdbrew** [comment]
@ishanivardhan 
There are a few different assignment pages in Moodle I think. The one in question is the TurnItIn activity.

I'd emulate the structure of the one on Anderson for now.

The design patterns used are tabs, tables, pagination and icons which are all in the framework.

Our test user (FT) is seeing the activity from a tutor perspective some how.

There should be as first importance a single table with one line telling me; the name of the document to upload, the start date and deadlines for the activity and an icon or function to upload. Clicking to upload opens a modal window allowing a file selection and a naming of the document.

Want to get the page functioning and then we can talk through the items?

**Comment by ishanivardhan** [comment]
Based on the feedback and walking through current assignment pages, comparing with local VC pages, there are a list of things to be pursued in order to get functional part of Assignment pages in shape & working.

Noting them in a separate [ticket](https://github.com/NHSLeadership/moodle-theme_nightingale/issues/69)

**Comment by ishanivardhan** [comment]
Closing this ticket as the query was answered by Jason and acted upon in the above ticket. any further enhancements can be pursued in a new ticket as required.
