### ISSUE TITLE
Bullet points don't show in lesson content

### ISSUE THREAD

**Issue by cehwitham** [NHSLeadership/nightingale-moodle#74]
https://hlmfacilitators.nhsx.uk/mod/lesson/view.php?id=2286

Above is an example of a bullet list in lesson content where the actual bullet points don't display.

`li {
    list-style: none;
}`

Should be changed to 

`li {
    list-style: disc;
}`

I believe.

**Comment by ishanivardhan** [comment]
Pushing for PR.
