### ISSUE TITLE
Quiz module styling

### ISSUE THREAD

**Issue by cehwitham** [NHSLeadership/nightingale-moodle#81]
* [x] Remove grey and blue background colours
* [x] Make "Question 2" a heading style
* [x] Previous page should be a secondary button
* [x] Add spacing between "Previous page" and "Finish attempt..." buttons
* [x] Does it make sense having the previous/next activity links on these pages? It feels like we have two sets of forward/back nav on this page?
* [x] Remove dropshadow type styling from the Quiz Navigation buttons.
* [x] Ensure radio buttons align with text https://hlmfacilitators.nhsx.uk/mod/lesson/view.php?id=2290&pageid=137

**Comment by ishanivardhan** [comment]
@cehwitham - For pt[4], I can edit the Navbuttons settings for HLM course to not show for Quiz activity. Will that help?

**Comment by ishanivardhan** [comment]
Also @cehwitham , I have removed the dropshadow but they seem to have lost their button-look. is this what you want?
<img width="749" alt="screen shot 2018-06-27 at 17 58 29" src="https://user-images.githubusercontent.com/25176815/41988362-bac9d112-7a33-11e8-84bd-94fc877bac02.png">

**Comment by ishanivardhan** [comment]
Raising a PR!
