### ISSUE TITLE
Answer box not constrained by container in lesson on HLM Campus

### ISSUE THREAD

**Issue by cehwitham** [NHSLeadership/nightingale-moodle#82]
https://hlmfacilitators.nhsx.uk/mod/lesson/view.php?id=2285&pageid=122

![screen shot 2018-06-22 at 15 21 44](https://user-images.githubusercontent.com/2518941/41781862-76c13eb2-7630-11e8-866b-e2b2e4b1e992.png)

The short answer / essay box is not constrained by the content container and runs off the edge of the screen. Should fill the content column.

**Comment by ishanivardhan** [comment]
Raising PR for this!
