### ISSUE TITLE
Error message styling amendment

### ISSUE THREAD

**Issue by cehwitham** [NHSLeadership/nightingale-moodle#84]
To recreate, visit a lesson with a short answer question in it. Submit without entering any text in the WYSIWYG window.

The error message should have a notification panel style and the continue button needs primary styling.

https://hlmfacilitators.nhsx.uk/mod/lesson/continue.php

![screen shot 2018-06-22 at 15 28 10](https://user-images.githubusercontent.com/2518941/41782079-13d7aad8-7631-11e8-95c3-a10cfc1b0efd.png)

**Comment by ishanivardhan** [comment]
Hi @cehwitham , the markup beneath this message has a selector `text_to_html` and not any error/warning classes around it hence it showed up as normal text. I have added blue card information styling.

The "Continue" button's markup by default has `btn btn-secondary` core classes attached to it, hence the styling of secondary button. Looking at the markup, there is no way to distinguish or use parent selectors to identify this one Secondary button and give it primary styling.

Any thoughts?

**Comment by ishanivardhan** [comment]
Raising a PR for now with what it will look like. Any further changes will be incorporated a spart of the PR review.
